using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using UnityEngine;

public class ControllerIALearning : ControllerAbstract
{
    // Start is called before the first frame update
    public override float GetRotation()
    {
        throw new System.NotImplementedException();
    }

    public override bool IsUsingPrimaryBonus()
    {
        throw new System.NotImplementedException();
    }

    public override bool IsUsingSecondaryBonus()
    {
        throw new System.NotImplementedException();
    }

    public string run_cmd(string cmd, string args)
    {
        ProcessStartInfo start = new ProcessStartInfo();
        start.FileName = Application.dataPath + "/Data/" + "predict.py";
        start.Arguments = string.Format("\"{0}\" \"{1}\"", cmd, args);
        start.UseShellExecute = false;// Do not use OS shell
        start.CreateNoWindow = true; // We don't need new window
        start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
        start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)
        using (Process process = Process.Start(start))
        {
            using (StreamReader reader = process.StandardOutput)
            {
                string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script
                string result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")
                return result;
            }
        }
    }
}
